import type { CategoryId } from "@/types/game";

export const PROMPTS: Record<CategoryId, string[]> = {
  mixta: [
    "Decí 3 cosas que llevarías a una isla desierta.",
    "Nombrá 3 personajes de películas que todos conozcan.",
    "Decí 3 cosas que harías si fueras invisible por una hora.",
    "Nombrá 3 profesiones que empiecen con la letra P.",
    "Decí 3 cosas que no podés hacer bien.",
    "Nombrá 3 cosas que siempre se pierden en tu casa.",
    "Decí 3 cosas que te dan vergüenza admitir.",
    "Nombrá 3 cosas que harías con un millón de pesos.",
    "Decí 3 palabras que te cueste pronunciar.",
    "Nombrá 3 cosas que te ponen de buen humor.",
    "Decí 3 cosas que no harías ni por plata.",
    "Nombrá 3 cosas que te gustaría aprender este año.",
    "Decí 3 cosas que siempre decís y no cumplís.",
    "Nombrá 3 cosas que odia tu yo del futuro.",
    "Decí 3 cosas que harías si ganaras un viaje gratis.",
    "Nombrá 3 cosas que no pueden faltar en un cumpleaños.",
    "Decí 3 cosas que harías si tuvieras 15 minutos de fama.",
    "Nombrá 3 cosas que te dan risa aunque no deberían.",
    "Decí 3 cosas que siempre llegan tarde.",
    "Nombrá 3 cosas que te hacen sentir viejo/a.",
  ],
  animales: [
    "Nombrá 3 animales que vuelan.",
    "Decí 3 animales que viven en el agua.",
    "Nombrá 3 animales que podrías tener de mascota.",
    "Decí 3 animales que te dan miedo.",
    "Nombrá 3 animales que empiecen con la letra C.",
    "Decí 3 animales de granja.",
    "Nombrá 3 animales que cambian de color.",
    "Decí 3 animales que nadan muy rápido.",
    "Nombrá 3 animales que viven en el frío.",
    "Decí 3 animales que cantan o hacen ruido fuerte.",
    "Nombrá 3 animales que comen hojas.",
    "Decí 3 animales que no tienen patas.",
    "Nombrá 3 animales que salen de noche.",
    "Decí 3 animales que son buenos saltando.",
    "Nombrá 3 animales que aparecen en películas infantiles.",
    "Decí 3 animales que viven en Argentina.",
    "Nombrá 3 animales que se mueven lento.",
    "Decí 3 animales que tienen cola larga.",
    "Nombrá 3 animales que te gustaría ver de cerca.",
    "Decí 3 animales que hacen nido.",
  ],
  comida: [
    "Nombrá 3 comidas con queso.",
    "Decí 3 comidas que se comen con pan.",
    "Nombrá 3 postres con chocolate.",
    "Decí 3 comidas que se hacen al horno.",
    "Nombrá 3 cosas que le pondrías a una pizza.",
    "Decí 3 comidas que te gustan frías.",
    "Nombrá 3 comidas típicas de domingo en familia.",
    "Decí 3 frutas que empiecen con la letra M.",
    "Nombrá 3 cosas que no pueden faltar en un asado.",
    "Decí 3 comidas que se comen con cuchara.",
    "Nombrá 3 bebidas que tomás en verano.",
    "Decí 3 comidas que no comerías ni obligado/a.",
    "Nombrá 3 comidas que huelen mejor de lo que saben.",
    "Decí 3 comidas que te recuerdan a tu infancia.",
    "Nombrá 3 cosas dulces que podrías comer todos los días.",
    "Decí 3 comidas que se pueden hacer en 10 minutos.",
    "Nombrá 3 comidas que se comen con las manos.",
    "Decí 3 comidas que llevan arroz.",
    "Nombrá 3 comidas que te dan sueño.",
    "Decí 3 comidas que combinan bien con mate.",
  ],
  lugares: [
    "Nombrá 3 lugares donde te gustaría vivir un año.",
    "Decí 3 países que empiecen con la letra A.",
    "Nombrá 3 lugares de Argentina que recomendás.",
    "Decí 3 lugares donde hace mucho frío.",
    "Nombrá 3 lugares para ir de vacaciones con amigos.",
    "Decí 3 ciudades con mar.",
    "Nombrá 3 lugares donde perderías el celular seguro.",
    "Decí 3 lugares que visitarías si no costara nada.",
    "Nombrá 3 barrios o zonas lindas de tu ciudad.",
    "Decí 3 lugares donde no podés dormir bien.",
    "Nombrá 3 lugares con mucha gente.",
    "Decí 3 lugares para esconderse en una casa.",
    "Nombrá 3 lugares que aparecen en películas famosas.",
    "Decí 3 lugares donde comerías algo rico ahora mismo.",
    "Nombrá 3 lugares para ir en pareja.",
    "Decí 3 lugares que te dan paz.",
    "Nombrá 3 lugares que quedan lejos de tu casa.",
    "Decí 3 lugares donde harías una foto increíble.",
    "Nombrá 3 lugares que no visitarías ni gratis.",
    "Decí 3 lugares para esconderse de la lluvia.",
  ],
  argentina: [
    "Nombrá 3 cosas que no pueden faltar en un asado argentino.",
    "Decí 3 palabras bien argentinas.",
    "Nombrá 3 comidas típicas argentinas.",
    "Decí 3 lugares de Argentina para visitar en vacaciones.",
    "Nombrá 3 cosas que un argentino hace en domingo.",
    "Decí 3 personajes famosos de Argentina.",
    "Nombrá 3 cosas que se dicen distinto en Argentina que en otros países.",
    "Decí 3 cosas que siempre hay en una casa argentina.",
    "Nombrá 3 momentos para tomar mate.",
    "Decí 3 canciones o ritmos que suenan en una fiesta argentina.",
    "Nombrá 3 cosas que un argentino extraña cuando viaja.",
    "Decí 3 comidas que combinan con mate.",
    "Nombrá 3 cosas que pasan en un cumpleaños familiar argentino.",
    "Decí 3 cosas que un argentino puede arreglar con cinta y alambre.",
    "Nombrá 3 lugares típicos para encontrarse con amigos.",
    "Decí 3 cosas que se gritan en un partido de fútbol.",
    "Nombrá 3 cosas que siempre se llevan a la playa.",
    "Decí 3 comidas que se hacen en fiestas patrias.",
    "Nombrá 3 cosas que hacen única a una sobremesa argentina.",
    "Decí 3 cosas que todo argentino discute como si fuera experto.",
  ],
  cosas: [
    "Nombrá 3 cosas que usás todos los días.",
    "Decí 3 cosas que no funcionan sin batería.",
    "Nombrá 3 cosas que siempre hay en una mochila.",
    "Decí 3 cosas que se rompen si se caen al piso.",
    "Nombrá 3 cosas que no deberías dejar al sol.",
    "Decí 3 cosas que hay en una cocina.",
    "Nombrá 3 cosas que conectás a un enchufe.",
    "Decí 3 cosas que guardás en un cajón.",
    "Nombrá 3 cosas que te llevarías de camping.",
    "Decí 3 cosas que hacen ruido cuando se caen.",
    "Nombrá 3 cosas que se pueden reciclar.",
    "Decí 3 cosas que se usan para escribir.",
    "Nombrá 3 cosas que no podés encontrar cuando las buscás.",
    "Decí 3 cosas que comprarías para una casa nueva.",
    "Nombrá 3 cosas que se cargan con USB.",
    "Decí 3 cosas que se ponen en la mesa antes de comer.",
    "Nombrá 3 cosas que usás para limpiar.",
    "Decí 3 cosas que se abren con llave.",
    "Nombrá 3 cosas que siempre terminan desordenadas.",
    "Decí 3 cosas que harían falta para armar una fiesta sorpresa.",
  ],
};

export function allCategoryIds(): CategoryId[] {
  return Object.keys(PROMPTS) as CategoryId[];
}

export function promptsFor(categories: CategoryId[]): string[] {
  const ids = categories.length > 0 ? categories : allCategoryIds();
  return ids.flatMap((id) => PROMPTS[id]);
}
